version: "3"
services:
  nextcloud:
    image: nextcloud:27.0.0
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - OVERWRITECLIURL=${server_address} # is https://sub.domain.tld
      - OVERWRITEPROTOCOL=https
    volumes:
      # - ./data:/var/www/html
      - nextcloud:/var/www/html
    restart: unless-stopped
    ports:
    - 127.0.0.1:8380:80   
volumes:
  nextcloud:   
